// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// The app's runtime connection goes through a driver adapter (see src/lib/prisma.ts),
// but `prisma migrate` / introspection need a plain datasource url here too.
// Uses the unpooled (direct) Neon connection since DDL over a pgbouncer
// pooler is unreliable; runtime queries use the pooled DATABASE_URL instead.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL_UNPOOLED ?? process.env.DATABASE_URL!,
  },
});
